### ISSUE TITLE
dwoo 1.x docs

### ISSUE THREAD

**Issue by themightychris** [dwoo-project/dwoo#16]
Since you've taken over dwoo.org, the original dwoo docs are no longer available anywhere (that I can find at least). There are some issues with Dwoo 2 preventing me from migrating to it, and it seems that it is still regarded as a beta release.

The original Dwoo developer had told me on his forums that he had converted the wiki to static html and would be hosting it in perpetuity, but now they are not available anywhere and my developers working with dwoo 1.x are starting to run into divergences that make the dwoo 2.0 docs inapplicable to dwoo 1.x development (the dateFormat plugin for instance has a new name and uses date() formats instead of strftime()).

Would it be possible to obtain the static dwoo 1.x docs and put them online at a subdomain or subfolder of dwoo.org?

**Comment by emulienfou** [comment]
Dwoo has been re stylised with full 1.x and 2.x documentation, go to http://dwoo.org.
