### ISSUE TITLE
Allow single quotes in plugin parameters - (not only ",but also ')

### ISSUE THREAD

**Issue by MartinMuzatko** [dwoo-project/dwoo#25]
I was quite puzzled, that I get the output with the quotes.
When I used double quotes (as seen in other blocks/functions) they got removed during the compiling process.

```php
	public function begin($wrapper = 'div', array $rest = array()) {
	}
```

Not a major drawback, but it was something I wasn't prepared for :)
Thank you for any feedback.

**Comment by emulienfou** [comment]
Was only available for 2.x-dev branch, tested on 1.2.2 with success
