### ISSUE TITLE
Documentation links all broken for dwoo < 2

### ISSUE THREAD

**Issue by lrcg** [dwoo-project/dwoo#26]
The revitalisation of the Dwoo templating system is great and the new site looks great! However, in the course of the change, all links to documentation in pre 2.0 code are now broken. The content appears to be available, but not via the old links. 

For example, http://wiki.dwoo.org/index.php/IteratorVariables can now be found at https://github.com/emulienfou/dwoo/wiki/Iterator-Variables

Is there any way to add some redirects or URL rewrites to avoid breaking the links from existing code?

If that is not feasible, perhaps redirect to archive.org? For example: http://web.archive.org/web/20130404161246/http://wiki.dwoo.org/index.php/Main_Page

This is related to, and depends on the solution to, issue #16 .

**Comment by emulienfou** [comment]
Fixed
