### ISSUE TITLE
Extended Template Recompile

### ISSUE THREAD

**Issue by vasileioslaios** [dwoo-project/dwoo#31]
Hi,

i just noticed a issue that creates an infinitely loop in your program. If a template extends a template and the extended template is updated, then the template needs to be updated. This is happening but after the template re-compiles itself it won't stop the loop. This is done in Dwoo/Core.php in line 406-414. After $recompile variable is set to true it won't change to false. You have to update your code with  else { $recompile = false; } is order to stop the loop. Thanks

**Comment by emulienfou** [comment]
Deprecated issue, was true in 2.x-dev!
