### ISSUE TITLE
Compilation Error [ Google Analytics Code ]

### ISSUE THREAD

**Issue by marxvn** [dwoo-project/dwoo#32]
Hi,
I received an error message when compiling a file containing Google Analytics.
>Fatal error: Uncaught exception 'Dwoo\Exception\CompilationException' with message 'Compilation error at line 46 in "file:C:\xampp\htdocs\html_page/template\layout.html" : Parse error in "i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script','//www.google-analytics.com/analytics.js','ga'); ga('create', 'UA-26210XXX-5', 'auto'); ga('send', 'pageview'); </script> </head>  in C:\xampp\htdocs\html_page\lib\Dwoo\Compiler.php on line 1408

**Comment by KrYpTeD974** [comment]
Try adding a space before }   like this : 
push(arguments) }
