### ISSUE TITLE
LogicException on \Dwoo\Autoloader::register

### ISSUE THREAD

**Issue by tyurderi** [dwoo-project/dwoo#35]
got the following error when trying to setup the autoloader of dwoo: http://puu.sh/hTm1Z/431090bcbd.png

what am i doing wrong?

**Comment by Padrio** [comment]
Are you using the Composer Autoloader?

**Comment by fobo66** [comment]
I have the same problem. And I'm not using Composer Autoloader.

**Comment by emulienfou** [comment]
Is this problem still valid ?
Please test with last release: 1.2.2

**Comment by emulienfou** [comment]
No more method: **\Dwoo\Autoloader::register**.
