### ISSUE TITLE
XOR triggers T_CONSTANT_ENCAPSED_STRING

### ISSUE THREAD

**Issue by KrYpTeD974** [dwoo-project/dwoo#37]
I'm trying to use a XOR condition like this : 

            {if $cond_a xor $cond_b}
                {$foo = 'foo'}
            {/if}

but I get a T_CONSTANT_ENCAPSED_STRING

The documentation says about the IF : Conditional block, the syntax is very similar to the php one, allowing () || && and **other php operators**.
So i guess there's an issue.
I use PHP 5.3.3

**Comment by emulienfou** [comment]
Operator `xor` and `^` have been added to 1.3.0 release who is steel in development status.

**Comment by emulienfou** [comment]
Also planned for 1.2.x, see issues: https://gitlab.com/dwooproject/dwoo/issues
