### ISSUE TITLE
Dead yet?

### ISSUE THREAD

**Issue by aolko** [dwoo-project/dwoo#39]
oh come on, last update was ~10 months ago
smarty last updated last month, wtf?

**Comment by aolko** [comment]
...yep, still dead

**Comment by Padrio** [comment]
I think this project is dead.

**Comment by aolko** [comment]
well, *smarty* then?

**Comment by Padrio** [comment]
Maybe check out: http://www.sitecrafting.com/blog/top-5-php-template-engines/

**Comment by aolko** [comment]
**Blade**
Not standalone

**Mustache**
JS

**Smarty**
The right choice

**Twig**
Meh...

**Volt**
Not standalone

**Comment by Padrio** [comment]
There is a mustache port for PHP

**Comment by emulienfou** [comment]
Sorry guys, I don't have a lots of time to manage this project anymore.

**Comment by aolko** [comment]
yup, dead, **confirmed**

**Comment by emulienfou** [comment]
So after a while, just decide to get back to dwoo for new developments so, not yet dead :)

**Comment by themightychris** [comment]
I use dwoo pretty heavily, it definitely isn't dead, just stable enough to not need constant work... Smarty is not a comparable replacement
