### ISSUE TITLE
Consider Contributing Documentation/docset to Dash?

### ISSUE THREAD

**Issue by sators** [dwoo-project/dwoo#40]
Hello,

As a Dash user, perhaps you might be up for considering to add your documentation to the Dash app?

https://kapeli.com/dash
https://kapeli.com/docsets

**Comment by emulienfou** [comment]
I'm not using OS X, I'm on linux and won't use dash for the documentation.

I recently redesign the site including 1.x and 2.x documentations using Jekyll and Markdown language to provide a full documentation.

**Comment by sators** [comment]
While you aren't using OS X, your users are.  If you ever consider it in the future, you could use npm to port your Markdown to a compatible format: https://www.npmjs.com/package/dash-docset-generator
