### ISSUE TITLE
Incompatibility with PHP 7

### ISSUE THREAD

**Issue by domymg** [dwoo-project/dwoo#44]
There is a bug when you try to use Dwoo with PHP7. When try to acess from a template to a object var.

It is in Core class, in readVarInto:
`$data = $data->$m[2][$k];`

has to be:

```
$attr = $m[2][$k];
$data = $data->$attr;
```

**Comment by emulienfou** [comment]
Dwoo move to GitLab, this bug has been fixed to the 1.3.0 release who will be out soon!

**Comment by themightychris** [comment]
@emulienfou is this GitLab repository public? I wasn't able to find it but it looks like this github repo IS active...

**Comment by emulienfou** [comment]
Hi, @themightychris just redefine all my development process for this project. This project is still hosted on GitHub has a public repository.

Hi, also had now a private mirrored repository hosted on GitLab to the future development with Continuous Integration.

PHPUnit tests are still available and will continued to be used is the future. The **1.2.x** and **`.3.x** versions are now tested on **PHP5.3** to **PHP5.6** for improve more stability on the future deliveries.

**Comment by emulienfou** [comment]
To answer to this issue, **YES** a future **1.4.0** is now in the development process to be compatible by **PHP7.x**

**Comment by themightychris** [comment]
@emulienfou is 1.4.0 what you're working on in the current master branch here on GitHub? I might contribute to that effort if it is happening on GitHub

**Comment by emulienfou** [comment]
Here is a view of the future works for Dwoo, how I put a final version on the public repository:

GitHub
---------
* `master` branch is up to date with the latest stable release, this branch is updated from **PullRequest** only from the last stable release (all branches included).
* `1.2` branch is up to date with the latest stable release of **1.2.x**, for now it's **1.2.3** and will be merged from the same branch from GitLab.

GitLab
--------
* `1.2` branch with latest works, current devs and test are here. Ready for next public release.
* `1.3` branch is currently in development with fix and new features (such as namespaces), this is a **BC Break** of `1.2.x`.
* `1.4` branch will be only compatible with **PHP7** and recent **ONLY**.

Here is the future timeline of developments of this project.

> If you want to contribute on this project it will be really appreciated, you can send me a private message with your GitLab login to give you access to my repository.

**Comment by themightychris** [comment]
@emulienfou so the 1.4 branch is not accessible anywhere public yet? Could you push that to github when you get the chance so I might try it out and contribute PRs?

**Comment by emulienfou** [comment]
Like I said, I'm working on the 1.3 branch, the 1.4 is not yet create. If you want to contribute I can give you access to my GitLab repository.

**Comment by themightychris** [comment]
@emulienfou thanks I would appreciate that!

**Comment by emulienfou** [comment]
Fixed from 1.3.1 release, now compatible with **PHP7.0** and **PHP7.1**.
