### ISSUE TITLE
Compiled template directory

### ISSUE THREAD

**Issue by ghost3k** [dwoo-project/dwoo#58]
Upgraded from Dwoo 1.2.0 to 1.3.3. It seems the compile directory is no longer used, and the compiled template files are placed in the same directory as the source template. Is this by design?
Using setCompileDir() does nothing now.

I fixed it back by changing lib/Dwoo/Template/File.php, function getCompiledFilename:
old line:
 return $this->compileId . '.d' . Core::RELEASE_TAG . '.php';
my fixed line:
 return $core->getCompileDir() . $this->compileId . '.d' . Core::RELEASE_TAG . '.php';

This was the initial line, but was changed in a commit on Sep 22, 2016.

Thanks!

**Comment by emulienfou** [comment]
Hi! I'm aware about this bug, this change was made because using `{include}` function who generated an error.
However my fix was not a good idea!
Trying to do a better fix ASAP.

**Comment by creativecat** [comment]
Thank you... I was searching for fixing exactly this bug... works fine for me :-)
