### ISSUE TITLE
What about the 2.0?

### ISSUE THREAD

**Issue by creativecat** [dwoo-project/dwoo#60]
I'm wondering what happened to the plans for 2.0? I read something about it years ago but didn't get more than a beta version. On GitHub I even can't find a repository or brand...
Latest news I could find were postet in november 2015...
I'm using Dwoo in many projects and love the simplicity. But I hoped for new features and maybe better efficiency.

**Comment by emulienfou** [comment]
Hi!
Dwoo 2.0 is no more in the future release, this version stays in beta version for a while but with a lots of bugs and was never finished.

All fixes, new features and updates has been taken from 2.0 to be putted on the 1.3.0 release.

There is no new features for the future release, a full PHP7 compatible only is on track to add faster and better code.

If you want new features, feel free to submit pull request.

For your information, a new repository for only users contributed plugins is available here: https://github.com/dwoo-project/community-plugins and will be updated as soon as possible with new plugins.

Best regards
